version: "3.8"
services:
  schema-registry:
    image: confluentinc/cp-schema-registry:${SCHEMA_REGISTRY_IMAGE_TAG}
    ports:
      - "8081:8081"
    environment:
        SCHEMA_REGISTRY_HOST_NAME: datadelivery-schema-registry
        SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081/
        SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: ${KAFKA_PROTOCOL}
        SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: PLAIN
        SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${KAFKA_KEY}\" password=\"${KAFKA_SECRET}\";
        SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP}
        SCHEMA_REGISTRY_KAFKASTORE_TOPIC: ${KAFKA_SCHEMA_TOPIC}
        SCHEMA_REGISTRY_SCHEMA_REGISTRY_GROUP_ID: ${KAFKA_SCHEMAREGISTRY_GROUPID}
