apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: datadelivery-schema-registry
  name: datadelivery-schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadelivery-schema-registry
  template:
    metadata:
      labels:
        app: datadelivery-schema-registry
    spec:
      containers:
        - image: confluentinc/cp-schema-registry:6.2.0 # TODO: Paremetrize tag
          name: cp-schema-registry
          imagePullPolicy: always
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: datadelivery-schema-registry
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081/
            - name: SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL
              value: SASL_SSL
            - name: SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM
              value: PLAIN
            - name: SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: datadelivery-schema-registry
                  key: SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: datadelivery-schema-registry
                  key: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
            - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC
              valueFrom:
                secretKeyRef:
                  name: datadelivery-schema-registry
                  key: SCHEMA_REGISTRY_KAFKASTORE_TOPIC
            - name: SCHEMA_REGISTRY_SCHEMA_REGISTRY_GROUP_ID
              valueFrom:
                secretKeyRef:
                  name: datadelivery-schema-registry
                  key: SCHEMA_REGISTRY_SCHEMA_REGISTRY_GROUP_ID
