apiVersion: v1
kind: Secret
metadata:
  name: datadelivery-schema-registry
type: Opaque
stringData:
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: $(SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS)
  SCHEMA_REGISTRY_KAFKASTORE_TOPIC: $(SCHEMA_REGISTRY_KAFKASTORE_TOPIC)
  SCHEMA_REGISTRY_SCHEMA_REGISTRY_GROUP_ID: $(SCHEMA_REGISTRY_SCHEMA_REGISTRY_GROUP_ID)
  SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$(KAFKA_KEY)\" password=\"$(KAFKA_SECRET)\";
  SCHEMA_REGISTRY_CONFLUENT_LICENSE_TOPIC: $(SCHEMA_REGISTRY_CONFLUENT_LICENSE_TOPIC)
  JAAS_CONFIG: |
    JDBCLoginModule {
      org.eclipse.jetty.jaas.spi.JDBCLoginModule required
      debug="true"
      dbUrl="jdbc:postgresql://database:5432/schemaregistry?user=postgres&password=p"
      dbUserName="postgres"
      dbDriver="org.postgresql.Driver"
      userTable="users"
      userField="user"
      credentialField="password"
      userRoleTable="userroles"
      userRoleUserField="user"
      userRoleRoleField="role";
    };
